version: '3'

services:
    webapi:
        build: webapi/.
        ports:
            - "8001:80"

    storageservice:
        build: storageservice/.
        ports:
            - "8002:80"
        volumes:
            - storage:storage/:rw

volumes:
    storage:
